### Prompt 예시
- 파이썬 크롤링 코드를 공유해줘
- 사이트는 tr로 아루어져있고, tr 예시는 다음과 같아
- tr의 주요 정보를 판다스 행으로 만들어줘

```html
<tr>
						<td style="padding-left:10px;"><a href="/sise/sise_group_detail.naver?type=upjong&amp;no=298">가정용기기와용품</a></td>
						<td class="number">
				<span class="tah p11 red01">
				+5.53%
				</span>
			</td>
						<td class="number">21</td>
						<td class="number">12</td>
						<td class="number">4</td>
						<td class="number">5</td>
						<td class="tc"><div class="graph_type_1" style="width:80px;"><div class="graph_bar" style="width:71%;"><span class="graph_txt">71%</span></div></div></td>
					</tr>
```

---


### prompt 부연설명

#### 1. Table HTML 요소에 대한 설명

HTML에서 테이블을 구성하는 요소에는 다음과 같이 존재

- `table` (표 전체): 보통 `thead`와 `tbody`로 이루어져 있음
  - `thead` (열 정보): 열 이름 등 주요 정보를 담고 있으며, 생략되는 경우도 많음
  - `tbody` (표 본문): 실제 데이터를 담은 각 행들로 구성
    - `tr` (행, table row): 표에서 각 행에 대응
      - `td` (table data cell): 행 안에서 각 셀에 대응

**실제 테이블 예시:**
<table>
  <thead>
    <tr>
      <th>이름</th>
      <th>나이</th>
      <th>직업</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>김철수</td>
      <td>30</td>
      <td>개발자</td>
    </tr>
    <tr>
      <td>이영희</td>
      <td>25</td>
      <td>디자이너</td>
    </tr>
  </tbody>
</table>

```html
<table>
  <thead>
    <tr>
      <th>이름</th>
      <th>나이</th>
      <th>직업</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>김철수</td>
      <td>30</td>
      <td>개발자</td>
    </tr>
    <tr>
      <td>이영희</td>
      <td>25</td>
      <td>디자이너</td>
    </tr>
  </tbody>
</table>
```

#### 2. Pandas

- Pandas는 파이썬에서 테이블처럼 생긴 데이터를 능숙하게 다루는 라이브러리입.
- 만약 다루는 데이터가 테이블 형태라면, Pandas 사용을 추천
- Pandas를 사용하면 엑셀 내보내기, CSV 저장, 엑셀 불러오기 등을 쉽게 할 수 있음

## 코드

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 웹페이지 URL 설정
url = 'https://finance.naver.com/sise/sise_group.naver?type=upjong'

# 웹페이지 내용을 가져옴
response = requests.get(url)

# BeautifulSoup을 사용하여 HTML 파싱
soup = BeautifulSoup(response.text, 'html.parser')

# tr 태그를 찾아서 데이터 추출
table = soup.find('table')
rows = table.find_all('tr')

data = []
for row in rows:
    columns = row.find_all('td')
    if len(columns) > 0:
        try:
            category = columns[0].find('a').text.strip()
            change = columns[1].find('span', {'class': 'tah p11 red01'}).text.strip()
            number_1 = columns[2].text.strip()
            number_2 = columns[3].text.strip()
            number_3 = columns[4].text.strip()
            number_4 = columns[5].text.strip()
            graph_percent = columns[6].find('span', {'class': 'graph_txt'}).text.strip()

            data.append([category, change, number_1, number_2, number_3, number_4, graph_percent])
        except AttributeError:
            print("Some data is missing in this row")

# 데이터프레임 생성
df = pd.DataFrame(data, columns=['Category', 'Change', 'Number_1', 'Number_2', 'Number_3', 'Number_4', 'Graph_Percent'])

# 데이터프레임 출력
print(df)

Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
Some data is missing in this row
     Category  Change Number_1 Number_2 Number_3 Number_4 Graph_Percent
0          조선  +7.76%       23       14        2        7          100%
1      복합유틸리티  +6.03%        1        1        0        0           77%
2    가정용기기와용품  +5.53%       21       12        4        5           71%
3   무역회사와판매업체  +4.65%        6        5        0        1           59%
4        전기제품  +3.72%       63       42        8       13           47%
..        ...     ...      ...      ...      ...      ...           ...
56         기타  +0.17%     1199      692      129      378            2%
57  건강관리장비와용품  +0.11%       88       46       12       30            1%
58       복합기업  +0.06%       24       10        3       11            0%
59         가구  +0.06%       11        6        0        5            0%
60       창업투자  +0.05%      102       53       27       22            0%

[61 rows x 7 columns]

In [6]:
df

     Category  Change Number_1 Number_2 Number_3 Number_4 Graph_Percent
0          조선  +7.76%       23       14        2        7          100%
1      복합유틸리티  +6.03%        1        1        0        0           77%
2    가정용기기와용품  +5.53%       21       12        4        5           71%
3   무역회사와판매업체  +4.65%        6        5        0        1           59%
4        전기제품  +3.72%       63       42        8       13           47%
..        ...     ...      ...      ...      ...      ...           ...
56         기타  +0.17%     1199      692      129      378            2%
57  건강관리장비와용품  +0.11%       88       46       12       30            1%
58       복합기업  +0.06%       24       10        3       11            0%
59         가구  +0.06%       11        6        0        5            0%
60       창업투자  +0.05%      102       53       27       22            0%

[61 rows x 7 columns]

In [7]:
df.to_excel("data.xlsx")